#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.3.3
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'anacron.service' 'anacron.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.3.3
dpkg-maintscript-helper rm_conffile /etc/init/anacron.conf 2.3-26\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apm/event.d/anacron 2.3-28\~ -- "$@"
# End automatically added section
