#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.3.4
dpkg-maintscript-helper mv_conffile /etc/dhcp3/dhclient-enter-hooks.d/avahi-autoipd /etc/dhcp/dhclient-enter-hooks.d/avahi-autoipd 0.6.25-4\~ avahi-autoipd -- "$@"
dpkg-maintscript-helper mv_conffile /etc/dhcp3/dhclient-exit-hooks.d/zzz_avahi-autoipd /etc/dhcp/dhclient-exit-hooks.d/zzz_avahi-autoipd 0.6.25-4\~ avahi-autoipd -- "$@"
# End automatically added section
